version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: hotel_db_container
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-hotel_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hotel_network

  web:
    build: .
    container_name: hotel_web_conteiner
    restart: always
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-docker-local-key-example-12345
      - DB_NAME=hotel_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - hotel_network

volumes:
  postgres_data:

networks:
  hotel_network:
    driver: bridge
